env:
  - GO111MODULE=on
  - CODECOV_TOKEN=d69c06fd-3c3c-4938-b816-e438e9f994aa

language: go
go:
  - "1.10.x"
  - "1.11.x"
  - master

matrix:
  allow_failures:
    - go: master

script:
  - go get -t -v ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)